# coding: utf-8

"""
    Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ClientDetailResponseResponseDetailOnboarding(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'average_run_duration': 'str',
        'max_run_duration': 'str',
        'average_assoc_duration': 'str',
        'max_assoc_duration': 'str',
        'average_auth_duration': 'str',
        'max_auth_duration': 'str',
        'average_dhcp_duration': 'str',
        'max_dhcp_duration': 'str',
        'aaa_server_ip': 'str',
        'dhcp_server_ip': 'str',
        'auth_done_time': 'str',
        'assoc_done_time': 'str',
        'dhcp_done_time': 'str'
    }

    attribute_map = {
        'average_run_duration': 'averageRunDuration',
        'max_run_duration': 'maxRunDuration',
        'average_assoc_duration': 'averageAssocDuration',
        'max_assoc_duration': 'maxAssocDuration',
        'average_auth_duration': 'averageAuthDuration',
        'max_auth_duration': 'maxAuthDuration',
        'average_dhcp_duration': 'averageDhcpDuration',
        'max_dhcp_duration': 'maxDhcpDuration',
        'aaa_server_ip': 'aaaServerIp',
        'dhcp_server_ip': 'dhcpServerIp',
        'auth_done_time': 'authDoneTime',
        'assoc_done_time': 'assocDoneTime',
        'dhcp_done_time': 'dhcpDoneTime'
    }

    def __init__(self, average_run_duration=None, max_run_duration=None, average_assoc_duration=None, max_assoc_duration=None, average_auth_duration=None, max_auth_duration=None, average_dhcp_duration=None, max_dhcp_duration=None, aaa_server_ip=None, dhcp_server_ip=None, auth_done_time=None, assoc_done_time=None, dhcp_done_time=None):  # noqa: E501
        """ClientDetailResponseResponseDetailOnboarding - a model defined in Swagger"""  # noqa: E501

        self._average_run_duration = None
        self._max_run_duration = None
        self._average_assoc_duration = None
        self._max_assoc_duration = None
        self._average_auth_duration = None
        self._max_auth_duration = None
        self._average_dhcp_duration = None
        self._max_dhcp_duration = None
        self._aaa_server_ip = None
        self._dhcp_server_ip = None
        self._auth_done_time = None
        self._assoc_done_time = None
        self._dhcp_done_time = None
        self.discriminator = None

        if average_run_duration is not None:
            self.average_run_duration = average_run_duration
        if max_run_duration is not None:
            self.max_run_duration = max_run_duration
        if average_assoc_duration is not None:
            self.average_assoc_duration = average_assoc_duration
        if max_assoc_duration is not None:
            self.max_assoc_duration = max_assoc_duration
        if average_auth_duration is not None:
            self.average_auth_duration = average_auth_duration
        if max_auth_duration is not None:
            self.max_auth_duration = max_auth_duration
        if average_dhcp_duration is not None:
            self.average_dhcp_duration = average_dhcp_duration
        if max_dhcp_duration is not None:
            self.max_dhcp_duration = max_dhcp_duration
        if aaa_server_ip is not None:
            self.aaa_server_ip = aaa_server_ip
        if dhcp_server_ip is not None:
            self.dhcp_server_ip = dhcp_server_ip
        if auth_done_time is not None:
            self.auth_done_time = auth_done_time
        if assoc_done_time is not None:
            self.assoc_done_time = assoc_done_time
        if dhcp_done_time is not None:
            self.dhcp_done_time = dhcp_done_time

    @property
    def average_run_duration(self):
        """Gets the average_run_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501


        :return: The average_run_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :rtype: str
        """
        return self._average_run_duration

    @average_run_duration.setter
    def average_run_duration(self, average_run_duration):
        """Sets the average_run_duration of this ClientDetailResponseResponseDetailOnboarding.


        :param average_run_duration: The average_run_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :type: str
        """

        self._average_run_duration = average_run_duration

    @property
    def max_run_duration(self):
        """Gets the max_run_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501


        :return: The max_run_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :rtype: str
        """
        return self._max_run_duration

    @max_run_duration.setter
    def max_run_duration(self, max_run_duration):
        """Sets the max_run_duration of this ClientDetailResponseResponseDetailOnboarding.


        :param max_run_duration: The max_run_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :type: str
        """

        self._max_run_duration = max_run_duration

    @property
    def average_assoc_duration(self):
        """Gets the average_assoc_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501


        :return: The average_assoc_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :rtype: str
        """
        return self._average_assoc_duration

    @average_assoc_duration.setter
    def average_assoc_duration(self, average_assoc_duration):
        """Sets the average_assoc_duration of this ClientDetailResponseResponseDetailOnboarding.


        :param average_assoc_duration: The average_assoc_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :type: str
        """

        self._average_assoc_duration = average_assoc_duration

    @property
    def max_assoc_duration(self):
        """Gets the max_assoc_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501


        :return: The max_assoc_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :rtype: str
        """
        return self._max_assoc_duration

    @max_assoc_duration.setter
    def max_assoc_duration(self, max_assoc_duration):
        """Sets the max_assoc_duration of this ClientDetailResponseResponseDetailOnboarding.


        :param max_assoc_duration: The max_assoc_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :type: str
        """

        self._max_assoc_duration = max_assoc_duration

    @property
    def average_auth_duration(self):
        """Gets the average_auth_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501


        :return: The average_auth_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :rtype: str
        """
        return self._average_auth_duration

    @average_auth_duration.setter
    def average_auth_duration(self, average_auth_duration):
        """Sets the average_auth_duration of this ClientDetailResponseResponseDetailOnboarding.


        :param average_auth_duration: The average_auth_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :type: str
        """

        self._average_auth_duration = average_auth_duration

    @property
    def max_auth_duration(self):
        """Gets the max_auth_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501


        :return: The max_auth_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :rtype: str
        """
        return self._max_auth_duration

    @max_auth_duration.setter
    def max_auth_duration(self, max_auth_duration):
        """Sets the max_auth_duration of this ClientDetailResponseResponseDetailOnboarding.


        :param max_auth_duration: The max_auth_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :type: str
        """

        self._max_auth_duration = max_auth_duration

    @property
    def average_dhcp_duration(self):
        """Gets the average_dhcp_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501


        :return: The average_dhcp_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :rtype: str
        """
        return self._average_dhcp_duration

    @average_dhcp_duration.setter
    def average_dhcp_duration(self, average_dhcp_duration):
        """Sets the average_dhcp_duration of this ClientDetailResponseResponseDetailOnboarding.


        :param average_dhcp_duration: The average_dhcp_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :type: str
        """

        self._average_dhcp_duration = average_dhcp_duration

    @property
    def max_dhcp_duration(self):
        """Gets the max_dhcp_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501


        :return: The max_dhcp_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :rtype: str
        """
        return self._max_dhcp_duration

    @max_dhcp_duration.setter
    def max_dhcp_duration(self, max_dhcp_duration):
        """Sets the max_dhcp_duration of this ClientDetailResponseResponseDetailOnboarding.


        :param max_dhcp_duration: The max_dhcp_duration of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :type: str
        """

        self._max_dhcp_duration = max_dhcp_duration

    @property
    def aaa_server_ip(self):
        """Gets the aaa_server_ip of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501


        :return: The aaa_server_ip of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :rtype: str
        """
        return self._aaa_server_ip

    @aaa_server_ip.setter
    def aaa_server_ip(self, aaa_server_ip):
        """Sets the aaa_server_ip of this ClientDetailResponseResponseDetailOnboarding.


        :param aaa_server_ip: The aaa_server_ip of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :type: str
        """

        self._aaa_server_ip = aaa_server_ip

    @property
    def dhcp_server_ip(self):
        """Gets the dhcp_server_ip of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501


        :return: The dhcp_server_ip of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :rtype: str
        """
        return self._dhcp_server_ip

    @dhcp_server_ip.setter
    def dhcp_server_ip(self, dhcp_server_ip):
        """Sets the dhcp_server_ip of this ClientDetailResponseResponseDetailOnboarding.


        :param dhcp_server_ip: The dhcp_server_ip of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :type: str
        """

        self._dhcp_server_ip = dhcp_server_ip

    @property
    def auth_done_time(self):
        """Gets the auth_done_time of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501


        :return: The auth_done_time of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :rtype: str
        """
        return self._auth_done_time

    @auth_done_time.setter
    def auth_done_time(self, auth_done_time):
        """Sets the auth_done_time of this ClientDetailResponseResponseDetailOnboarding.


        :param auth_done_time: The auth_done_time of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :type: str
        """

        self._auth_done_time = auth_done_time

    @property
    def assoc_done_time(self):
        """Gets the assoc_done_time of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501


        :return: The assoc_done_time of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :rtype: str
        """
        return self._assoc_done_time

    @assoc_done_time.setter
    def assoc_done_time(self, assoc_done_time):
        """Sets the assoc_done_time of this ClientDetailResponseResponseDetailOnboarding.


        :param assoc_done_time: The assoc_done_time of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :type: str
        """

        self._assoc_done_time = assoc_done_time

    @property
    def dhcp_done_time(self):
        """Gets the dhcp_done_time of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501


        :return: The dhcp_done_time of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :rtype: str
        """
        return self._dhcp_done_time

    @dhcp_done_time.setter
    def dhcp_done_time(self, dhcp_done_time):
        """Sets the dhcp_done_time of this ClientDetailResponseResponseDetailOnboarding.


        :param dhcp_done_time: The dhcp_done_time of this ClientDetailResponseResponseDetailOnboarding.  # noqa: E501
        :type: str
        """

        self._dhcp_done_time = dhcp_done_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClientDetailResponseResponseDetailOnboarding):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
