# coding: utf-8

"""
    Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DeviceInnerDeviceInfoFileSystemList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'freespace': 'int',
        'name': 'str',
        'readable': 'bool',
        'size': 'int',
        'type': 'str',
        'writeable': 'bool'
    }

    attribute_map = {
        'freespace': 'freespace',
        'name': 'name',
        'readable': 'readable',
        'size': 'size',
        'type': 'type',
        'writeable': 'writeable'
    }

    def __init__(self, freespace=None, name=None, readable=None, size=None, type=None, writeable=None):  # noqa: E501
        """DeviceInnerDeviceInfoFileSystemList - a model defined in Swagger"""  # noqa: E501

        self._freespace = None
        self._name = None
        self._readable = None
        self._size = None
        self._type = None
        self._writeable = None
        self.discriminator = None

        if freespace is not None:
            self.freespace = freespace
        if name is not None:
            self.name = name
        if readable is not None:
            self.readable = readable
        if size is not None:
            self.size = size
        if type is not None:
            self.type = type
        if writeable is not None:
            self.writeable = writeable

    @property
    def freespace(self):
        """Gets the freespace of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501


        :return: The freespace of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501
        :rtype: int
        """
        return self._freespace

    @freespace.setter
    def freespace(self, freespace):
        """Sets the freespace of this DeviceInnerDeviceInfoFileSystemList.


        :param freespace: The freespace of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501
        :type: int
        """

        self._freespace = freespace

    @property
    def name(self):
        """Gets the name of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501


        :return: The name of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DeviceInnerDeviceInfoFileSystemList.


        :param name: The name of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def readable(self):
        """Gets the readable of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501


        :return: The readable of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501
        :rtype: bool
        """
        return self._readable

    @readable.setter
    def readable(self, readable):
        """Sets the readable of this DeviceInnerDeviceInfoFileSystemList.


        :param readable: The readable of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501
        :type: bool
        """

        self._readable = readable

    @property
    def size(self):
        """Gets the size of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501


        :return: The size of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this DeviceInnerDeviceInfoFileSystemList.


        :param size: The size of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def type(self):
        """Gets the type of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501


        :return: The type of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DeviceInnerDeviceInfoFileSystemList.


        :param type: The type of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def writeable(self):
        """Gets the writeable of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501


        :return: The writeable of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501
        :rtype: bool
        """
        return self._writeable

    @writeable.setter
    def writeable(self, writeable):
        """Sets the writeable of this DeviceInnerDeviceInfoFileSystemList.


        :param writeable: The writeable of this DeviceInnerDeviceInfoFileSystemList.  # noqa: E501
        :type: bool
        """

        self._writeable = writeable

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceInnerDeviceInfoFileSystemList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
