# coding: utf-8

"""
    Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DeviceInnerDeviceInfoLocation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'altitude': 'str',
        'latitude': 'str',
        'longitude': 'str',
        'site_id': 'str'
    }

    attribute_map = {
        'address': 'address',
        'altitude': 'altitude',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'site_id': 'siteId'
    }

    def __init__(self, address=None, altitude=None, latitude=None, longitude=None, site_id=None):  # noqa: E501
        """DeviceInnerDeviceInfoLocation - a model defined in Swagger"""  # noqa: E501

        self._address = None
        self._altitude = None
        self._latitude = None
        self._longitude = None
        self._site_id = None
        self.discriminator = None

        if address is not None:
            self.address = address
        if altitude is not None:
            self.altitude = altitude
        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude
        if site_id is not None:
            self.site_id = site_id

    @property
    def address(self):
        """Gets the address of this DeviceInnerDeviceInfoLocation.  # noqa: E501


        :return: The address of this DeviceInnerDeviceInfoLocation.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this DeviceInnerDeviceInfoLocation.


        :param address: The address of this DeviceInnerDeviceInfoLocation.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def altitude(self):
        """Gets the altitude of this DeviceInnerDeviceInfoLocation.  # noqa: E501


        :return: The altitude of this DeviceInnerDeviceInfoLocation.  # noqa: E501
        :rtype: str
        """
        return self._altitude

    @altitude.setter
    def altitude(self, altitude):
        """Sets the altitude of this DeviceInnerDeviceInfoLocation.


        :param altitude: The altitude of this DeviceInnerDeviceInfoLocation.  # noqa: E501
        :type: str
        """

        self._altitude = altitude

    @property
    def latitude(self):
        """Gets the latitude of this DeviceInnerDeviceInfoLocation.  # noqa: E501


        :return: The latitude of this DeviceInnerDeviceInfoLocation.  # noqa: E501
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this DeviceInnerDeviceInfoLocation.


        :param latitude: The latitude of this DeviceInnerDeviceInfoLocation.  # noqa: E501
        :type: str
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this DeviceInnerDeviceInfoLocation.  # noqa: E501


        :return: The longitude of this DeviceInnerDeviceInfoLocation.  # noqa: E501
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this DeviceInnerDeviceInfoLocation.


        :param longitude: The longitude of this DeviceInnerDeviceInfoLocation.  # noqa: E501
        :type: str
        """

        self._longitude = longitude

    @property
    def site_id(self):
        """Gets the site_id of this DeviceInnerDeviceInfoLocation.  # noqa: E501


        :return: The site_id of this DeviceInnerDeviceInfoLocation.  # noqa: E501
        :rtype: str
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id):
        """Sets the site_id of this DeviceInnerDeviceInfoLocation.


        :param site_id: The site_id of this DeviceInnerDeviceInfoLocation.  # noqa: E501
        :type: str
        """

        self._site_id = site_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceInnerDeviceInfoLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
