# coding: utf-8

"""
    Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from python_client.models.image_info_list_response_response import ImageInfoListResponseResponse  # noqa: F401,E501


class ImageInfoListResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'response': 'list[ImageInfoListResponseResponse]',
        'version': 'str'
    }

    attribute_map = {
        'response': 'response',
        'version': 'version'
    }

    def __init__(self, response=None, version=None):  # noqa: E501
        """ImageInfoListResponse - a model defined in Swagger"""  # noqa: E501

        self._response = None
        self._version = None
        self.discriminator = None

        if response is not None:
            self.response = response
        if version is not None:
            self.version = version

    @property
    def response(self):
        """Gets the response of this ImageInfoListResponse.  # noqa: E501


        :return: The response of this ImageInfoListResponse.  # noqa: E501
        :rtype: list[ImageInfoListResponseResponse]
        """
        return self._response

    @response.setter
    def response(self, response):
        """Sets the response of this ImageInfoListResponse.


        :param response: The response of this ImageInfoListResponse.  # noqa: E501
        :type: list[ImageInfoListResponseResponse]
        """

        self._response = response

    @property
    def version(self):
        """Gets the version of this ImageInfoListResponse.  # noqa: E501


        :return: The version of this ImageInfoListResponse.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ImageInfoListResponse.


        :param version: The version of this ImageInfoListResponse.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImageInfoListResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
