# coding: utf-8

"""
    Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from python_client.models.template_deployment_info_target_info import TemplateDeploymentInfoTargetInfo  # noqa: F401,E501


class TemplateDeploymentInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'target_info': 'list[TemplateDeploymentInfoTargetInfo]',
        'template_id': 'str'
    }

    attribute_map = {
        'target_info': 'targetInfo',
        'template_id': 'templateId'
    }

    def __init__(self, target_info=None, template_id=None):  # noqa: E501
        """TemplateDeploymentInfo - a model defined in Swagger"""  # noqa: E501

        self._target_info = None
        self._template_id = None
        self.discriminator = None

        if target_info is not None:
            self.target_info = target_info
        if template_id is not None:
            self.template_id = template_id

    @property
    def target_info(self):
        """Gets the target_info of this TemplateDeploymentInfo.  # noqa: E501


        :return: The target_info of this TemplateDeploymentInfo.  # noqa: E501
        :rtype: list[TemplateDeploymentInfoTargetInfo]
        """
        return self._target_info

    @target_info.setter
    def target_info(self, target_info):
        """Sets the target_info of this TemplateDeploymentInfo.


        :param target_info: The target_info of this TemplateDeploymentInfo.  # noqa: E501
        :type: list[TemplateDeploymentInfoTargetInfo]
        """

        self._target_info = target_info

    @property
    def template_id(self):
        """Gets the template_id of this TemplateDeploymentInfo.  # noqa: E501


        :return: The template_id of this TemplateDeploymentInfo.  # noqa: E501
        :rtype: str
        """
        return self._template_id

    @template_id.setter
    def template_id(self, template_id):
        """Sets the template_id of this TemplateDeploymentInfo.


        :param template_id: The template_id of this TemplateDeploymentInfo.  # noqa: E501
        :type: str
        """

        self._template_id = template_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TemplateDeploymentInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
